from tkinter import *
def solution():
    base = float(input_base.get())
    height = float(input_height.get())
    surface = round(1/2*(base * height), 2)
    hypotenuse = round(((base)**2 + (height)**2)**0.5,2)
    area_result.config(text=f'{surface} m2')
    hyppo_result.config(text=f'{hypotenuse} m')
window = Tk()
window.title('Triangle properties')
window.config(padx=20, pady=20, bg= 'sky blue')
triangle_base = Label(text= 'Base:',bg= 'sky blue')
triangle_base.grid(column=0, row = 0)
input_base = Entry(width=6)
input_base.grid(column=1, row = 0)
triangle_height = Label(text= 'Height:', bg= 'sky blue')
triangle_height.grid(column=3, row = 0)
input_height = Entry(width=6)
input_height.grid(column=4, row = 0)
triangle_area = Label(text='Area:', bg= 'red')
triangle_area.grid(column=0, row = 1)
triangle_hyppo = Label(text='Hyppotenuse:', bg= 'green')
triangle_hyppo.grid(column=2, row = 1)
area_result = Label(text='0', bg= 'sky blue')
area_result.grid(column=1, row = 1)
hyppo_result = Label(text='0', bg= 'sky blue')
hyppo_result.grid(column=3, row = 1)
calculate_button = Button(text='Calculate', bg= 'yellow', command=solution)
calculate_button.grid(column=2, row=3)
list1_box = Listbox(window, width=4, height=1, selectmode=MULTIPLE)
list1_box.insert(1, 'm')
list1_box.insert(1, 'cm')
list1_box.insert(1, 'km')
list1_box.grid(column=2, row=0)
list2_box = Listbox(window, width=4, height=1, selectmode=MULTIPLE)
list2_box.insert(1, 'm')
list2_box.insert(1, 'cm')
list2_box.insert(1, 'km')
list2_box.grid(column=6, row=0)

window.mainloop()
